Repository kgu-clab/clab-platforms, pull requests merged in 2024-06, with the labels that each got.

#157 번들러 마이그레이션 (rollup -> tsup)
  apps/auth/app/layout.tsx
  apps/member/src/main.tsx
  packages/design-system/package.json
  packages/design-system/rollup.config.js
  packages/design-system/tsup.config.ts
  pnpm-lock.yaml
Labels: 🔨 Refactor, 🏠 Member, 🧩 DesignSystem, 🔒 Auth

#168 프로젝트 환경 설정 변경
  .github/ISSUE_TEMPLATE/bug.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .nvmrc
  README.md
  packages/design-system/vitest.config.mjs
  pnpm-lock.yaml
Labels: ⚙ Setup, 🧩 DesignSystem

#170 docs: update README.md
  README.md
Labels: 🗂️ Documentation

#172 status 페이지 개발 및 BUG 48 수정
  apps/member/src/components/community/BoardCollectCard/BoardCollectCard.tsx
  apps/status/.gitignore
  apps/status/README.md
  apps/status/app/favicon.ico
  apps/status/app/globals.css
  apps/status/app/layout.tsx
  apps/status/app/page.tsx
  apps/status/next.config.mjs
  apps/status/package.json
  apps/status/postcss.config.mjs
  apps/status/public/image/logo.webp
  apps/status/public/lottie/inspection.json
  apps/status/public/next.svg
  apps/status/public/svg/github.svg
  apps/status/public/vercel.svg
  apps/status/src/shared/constant/index.ts
  apps/status/src/shared/constant/serviceList.ts
  apps/status/src/shared/index.ts
  apps/status/src/shared/type/index.ts
  apps/status/src/shared/type/service.ts
  apps/status/src/shared/ui/Title.tsx
  apps/status/src/shared/ui/index.ts
  apps/status/src/widgets/introduce/index.ts
  apps/status/src/widgets/introduce/ui/InspectionLottie.tsx
  apps/status/src/widgets/introduce/ui/Introduce.tsx
  apps/status/src/widgets/introduce/ui/index.ts
  apps/status/src/widgets/menu/index.ts
  apps/status/src/widgets/menu/ui/Footer.tsx
  apps/status/src/widgets/menu/ui/Header.tsx
  apps/status/src/widgets/menu/ui/index.ts
  apps/status/src/widgets/notification/index.ts
  apps/status/src/widgets/notification/ui/Notification.tsx
  apps/status/src/widgets/notification/ui/NotificationItem.tsx
  apps/status/src/widgets/notification/ui/index.ts
  apps/status/src/widgets/service-status/index.ts
  apps/status/src/widgets/service-status/ui/CurrentServices.tsx
  apps/status/src/widgets/service-status/ui/ServiceStatusItem.tsx
  apps/status/src/widgets/service-status/ui/index.ts
  apps/status/tailwind.config.ts
  apps/status/tsconfig.json
  commitlint.config.js
  package.json
  packages/config/clab.tailwind.preset.js
  pnpm-lock.yaml
Labels: 🐞 Bug, ✨ Feature, 📊 Status

#173 스테이터스 페이지 백엔드 연동 및 레이아웃 보완
  apps/status/app/layout.tsx
  apps/status/app/page.tsx
  apps/status/package.json
  apps/status/public/image/logo_primary.webp
  apps/status/public/image/logo_secondary.webp
  apps/status/public/lottie/inspection.json
  apps/status/public/lottie/working.json
  apps/status/src/shared/constant/serviceList.ts
  apps/status/src/widgets/introduce/ui/Introduce.tsx
  apps/status/src/widgets/introduce/ui/IntroduceLottie.tsx
  apps/status/src/widgets/menu/ui/Header.tsx
  apps/status/src/widgets/service-status/ui/CurrentServices.tsx
  apps/status/src/widgets/service-status/ui/ServiceStatusItem.tsx
  pnpm-lock.yaml
Labels: ✨ Feature, 🔨 Refactor, 📊 Status
