Repository kgu-clab/clab-platforms, pull requests merged in 2024-02, with the labels that each got.

#30 Feature(member)/oauth
  README.md
  apps/auth/app/api/auth.ts
  apps/auth/app/constants/api.ts
  apps/auth/app/hooks/queries/useTwoFactorLoginMutation.ts
  apps/auth/app/types/server.ts
  apps/auth/next.config.mjs
  apps/auth/package.json
  apps/member/package.json
  apps/member/src/App.tsx
  apps/member/src/components/common/LoginButton/LoginButton.tsx
  apps/member/src/components/common/Nav/Nav.tsx
  apps/member/src/components/my/ProfileSection/ProfileSection.tsx
  apps/member/src/components/router/ProtectAuth.tsx
  apps/member/src/constants/key.ts
  apps/member/src/constants/path.ts
  apps/member/src/hooks/common/.gitkeep
  apps/member/src/hooks/common/useToken.ts
  apps/member/src/pages/AuthPage/AuthPage.tsx
  apps/member/src/pages/ErrorPage/ErrorPage.tsx
  apps/member/src/pages/LoginPage/LoginPage.tsx
  apps/member/src/router/AppLayout.tsx
  apps/member/src/router/AppRouter.tsx
  apps/member/src/store/.gitkeep
  apps/member/src/store/auth.ts
  packages/design-system/src/Button/Button.tsx
  yarn.lock
Labels: ✨ Feature

#38 feat: 일정 API 연동
  apps/member/src/api/schedule.ts
  apps/member/src/components/calendar/AddSchedule/AddSchedule.tsx
  apps/member/src/components/calendar/CalendarSchedule/CalendarSchedule.tsx
  apps/member/src/components/calendar/CalendarSection/CalendarSection.tsx
  apps/member/src/pages/CalendarPage/CalendarPage.tsx
  apps/member/src/types/schedule.ts
Labels: ✨ Feature

#40 Auth API에 대한 자잘한 버그를 수정했습니다.
  .eslintrc.json
  apps/member/.eslintrc.cjs
  apps/member/src/components/common/Image/Image.tsx
  apps/member/src/components/panels/BookPanel/BookPanel.tsx
  apps/member/src/constants/path.ts
Labels: 🔨 Refactor

#41 Refactor/auth
  apps/member/src/api/interceptors.ts
  apps/member/src/api/member.ts
  apps/member/src/components/common/ImageBanner/ImageBanner.tsx
  apps/member/src/components/common/Panel/Panel.tsx
  apps/member/src/components/main/BirthdayList/BirthdayList.tsx
  apps/member/src/constants/key.ts
  apps/member/src/constants/path.ts
  apps/member/src/hooks/queries/useUserInfoMutation.ts
  apps/member/src/router/AppRouter.tsx
  apps/member/src/utils/api.ts
Labels: ✨ Feature, 🔨 Refactor

#45 커뮤니티 API 연동
  apps/member/src/api/accuse.ts
  apps/member/src/api/activity.ts
  apps/member/src/api/birthday.ts
  apps/member/src/api/blog.ts
  apps/member/src/api/board.ts
  apps/member/src/api/book.ts
  apps/member/src/api/comment.ts
  apps/member/src/api/community.ts
  apps/member/src/api/hire.ts
  apps/member/src/api/news.ts
  apps/member/src/api/notification.ts
  apps/member/src/api/schedule.ts
  apps/member/src/components/common/CommentInput/CommentInput.tsx
  apps/member/src/components/community/HireContentSection/HireContentSection.tsx
  apps/member/src/components/community/PostCommentSection/PostCommentSection.tsx
  apps/member/src/components/main/CommunitySection/CommunitySection.tsx
  apps/member/src/constants/api.ts
  apps/member/src/constants/key.ts
  apps/member/src/hooks/queries/useAccuses.ts
  apps/member/src/hooks/queries/useCommentList.ts
  apps/member/src/hooks/queries/useCommentWriteMutation.ts
  apps/member/src/hooks/queries/useCommunityList.ts
  apps/member/src/hooks/queries/useCommunityPost.ts
  apps/member/src/hooks/queries/useCommunityPostMutation.ts
  apps/member/src/hooks/queries/useCommunityWriteMutation.ts
  apps/member/src/hooks/queries/useHirePost.ts
  apps/member/src/hooks/queries/useNewsPost.ts
  apps/member/src/pages/CommunityDetailPage/CommunityDetailPage.tsx
  apps/member/src/pages/CommunityPage/CommunityPage.tsx
  apps/member/src/pages/CommunityPostPage/CommunityPostPage.tsx
  apps/member/src/pages/CommunityWritePage/CommunityWritePage.tsx
  apps/member/src/types/accuses.ts
  apps/member/src/types/comment.ts
  apps/member/src/types/community.ts
  apps/member/src/types/hire.ts
  apps/member/src/types/news.ts
  apps/member/src/types/post.ts
  apps/member/src/utils/api.ts
Labels: ✨ Feature

#46 Modal 컴포넌트를 설계했습니다.
  apps/member/src/components/common/Modal/Modal.tsx
  apps/member/src/components/common/ModalContainer/ModalContainer.tsx
  apps/member/src/components/common/Nav/Nav.tsx
  apps/member/src/components/common/SelectButton/SelectButton.tsx
  apps/member/src/components/main/CommunitySection/CommunitySection.tsx
  apps/member/src/components/panels/AlarmPanel/AlarmPanel.tsx
  apps/member/src/constants/key.ts
  apps/member/src/hooks/common/useModal.ts
  apps/member/src/main.tsx
  apps/member/src/pages/CommunityPage/CommunityPage.tsx
  apps/member/src/pages/MainPage/MainPage.tsx
  apps/member/src/store/modal.ts
Labels: ✨ Feature

#50 게시글 수정 기능을 추가합니다.
  apps/member/src/api/board.ts
  apps/member/src/api/comment.ts
  apps/member/src/api/community.ts
  apps/member/src/api/hire.ts
  apps/member/src/api/interceptors.ts
  apps/member/src/api/news.ts
  apps/member/src/components/common/CommentInput/CommentInput.tsx
  apps/member/src/components/common/Image/Image.tsx
  apps/member/src/components/common/Modal/Modal.tsx
  apps/member/src/components/common/Modal/ModalContainer.tsx
  apps/member/src/components/common/Post/Post.tsx
  apps/member/src/components/community/HireContentSection/HireContentSection.tsx
  apps/member/src/components/community/PostCommentSection/PostCommentSection.tsx
  apps/member/src/components/main/BirthdayList/BirthdayList.tsx
  apps/member/src/components/main/CommunitySection/CommunitySection.tsx
  apps/member/src/components/main/NewsCardSection/NewsCardSection.tsx
  apps/member/src/constants/api.ts
  apps/member/src/constants/key.ts
  apps/member/src/constants/message.ts
  apps/member/src/hooks/queries/useAccuses.ts
  apps/member/src/hooks/queries/useAccusesMutation.ts
  apps/member/src/hooks/queries/useBirthday.ts
  apps/member/src/hooks/queries/useBlog.ts
  apps/member/src/hooks/queries/useBoardModifyMutation.ts
  apps/member/src/hooks/queries/useBoardWriteMutation.ts
  apps/member/src/hooks/queries/useBoards.ts
  apps/member/src/hooks/queries/useCommentList.ts
  apps/member/src/hooks/queries/useCommunity.ts
  apps/member/src/hooks/queries/useCommunityList.ts
  apps/member/src/hooks/queries/useCommunityPost.ts
  apps/member/src/hooks/queries/useCommunityPostMutation.ts
  apps/member/src/hooks/queries/useCommunityWriteMutation.ts
  apps/member/src/hooks/queries/useHire.ts
  apps/member/src/hooks/queries/useHirePost.ts
  apps/member/src/hooks/queries/useMyBookLoan.ts
  apps/member/src/hooks/queries/useNews.ts
  apps/member/src/hooks/queries/useNewsPost.ts
  apps/member/src/hooks/queries/usePosts.ts
  apps/member/src/pages/CommunityDetailPage/CommunityDetailPage.tsx
  apps/member/src/pages/CommunityPage/CommunityPage.tsx
  apps/member/src/pages/CommunityPostPage/CommunityPostPage.tsx
  apps/member/src/pages/CommunityWritePage/CommunityWritePage.tsx
  apps/member/src/pages/MainPage/MainPage.tsx
  apps/member/src/types/community.ts
  apps/member/src/types/post.ts
  apps/member/src/utils/community.ts
Labels: ✨ Feature

#52 캘린더 컴포넌트를 개선합니다.
  apps/member/src/components/calendar/AddSchedule/AddSchedule.tsx
  apps/member/src/components/calendar/Calendar/Calendar.tsx
  apps/member/src/components/calendar/Calendar/Calendar.utils.tsx
  apps/member/src/components/calendar/CalendarSchedule/CalendarSchedule.tsx
  apps/member/src/components/calendar/CalendarSection/CalendarSection.tsx
  apps/member/src/constants/key.ts
  apps/member/src/constants/state.ts
  apps/member/src/hooks/queries/useSchedule.ts
  apps/member/src/pages/CalendarPage/CalendarPage.tsx
  apps/member/src/pages/MainPage/MainPage.tsx
  apps/member/src/types/schedule.ts
  apps/member/src/utils/date.ts
Labels: 🔨 Refactor

#53 회비 API 연동
  apps/member/src/api/membershipFee.ts
  apps/member/src/api/uploadedFile.ts
  apps/member/src/components/support/RequestForm/RequestForm.tsx
  apps/member/src/constants/api.ts
  apps/member/src/constants/key.ts
  apps/member/src/hooks/queries/useMembershipFee.ts
  apps/member/src/hooks/queries/useMembershipFeeMutation.ts
  apps/member/src/hooks/queries/useUploadedFileMembershipFeeMutation.ts
  apps/member/src/types/membershipFee.ts
  packages/design-system/src/Input/Input.tsx
Labels: ✨ Feature

#54 clab.page README.md에 자세한 소개와 다이어그램을 추가했습니다.
  README.md
Labels: 🗂️ Documentation

#55 도서관 API 연동
  apps/member/package.json
  apps/member/src/api/book.ts
  apps/member/src/components/library/BookCard/BookCard.tsx
  apps/member/src/components/library/BookDetailSection/BookDetailSection.tsx
  apps/member/src/components/library/LibraryBookList/LibraryBookList.tsx
  apps/member/src/components/library/LibraryNewBookSection/LibraryNewBookSection.tsx
  apps/member/src/components/library/LibraryOwnBookSection/LibraryOwnBookSection.tsx
  apps/member/src/components/panels/BookPanel/BookPanel.tsx
  apps/member/src/components/panels/PanelAside/PanelAside.tsx
  apps/member/src/constants/api.ts
  apps/member/src/constants/key.ts
  apps/member/src/constants/message.ts
  apps/member/src/constants/path.ts
  apps/member/src/constants/state.ts
  apps/member/src/hooks/common/useModal.ts
  apps/member/src/hooks/queries/useBookDetails.ts
  apps/member/src/hooks/queries/useBookLoanBorrowMutation.tsx
  apps/member/src/hooks/queries/useBookLoanExtendMutation.tsx
  apps/member/src/hooks/queries/useBookLoanRecordById.ts
  apps/member/src/hooks/queries/useBookLoanReturnMutation.tsx
  apps/member/src/hooks/queries/useBooks.ts
  apps/member/src/hooks/queries/useMyBookLoan.ts
  apps/member/src/pages/ErrorPage/ErrorPage.tsx
  apps/member/src/pages/LibraryDetailPage/LibraryDetailPage.tsx
  apps/member/src/pages/LibraryPage/LibraryPage.tsx
  apps/member/src/router/AppRouter.tsx
  apps/member/src/store/modal.ts
  apps/member/src/types/book.ts
  apps/member/vite.config.ts
  package.json
  yarn.lock
Labels: ✨ Feature, 🔨 Refactor

#56 회비, 도서관 API 연동 완료
  apps/member/package.json
  apps/member/src/api/book.ts
  apps/member/src/api/membershipFee.ts
  apps/member/src/api/uploadedFile.ts
  apps/member/src/components/calendar/AddSchedule/AddSchedule.tsx
  apps/member/src/components/calendar/Calendar/Calendar.tsx
  apps/member/src/components/calendar/Calendar/Calendar.utils.tsx
  apps/member/src/components/calendar/CalendarSchedule/CalendarSchedule.tsx
  apps/member/src/components/calendar/CalendarSection/CalendarSection.tsx
  apps/member/src/components/library/BookCard/BookCard.tsx
  apps/member/src/components/library/BookDetailSection/BookDetailSection.tsx
  apps/member/src/components/library/LibraryBookList/LibraryBookList.tsx
  apps/member/src/components/library/LibraryNewBookSection/LibraryNewBookSection.tsx
  apps/member/src/components/library/LibraryOwnBookSection/LibraryOwnBookSection.tsx
  apps/member/src/components/panels/BookPanel/BookPanel.tsx
  apps/member/src/components/panels/PanelAside/PanelAside.tsx
  apps/member/src/components/support/RequestForm/RequestForm.tsx
  apps/member/src/constants/api.ts
  apps/member/src/constants/key.ts
  apps/member/src/constants/message.ts
  apps/member/src/constants/path.ts
  apps/member/src/constants/state.ts
  apps/member/src/hooks/common/useModal.ts
  apps/member/src/hooks/queries/useBookDetails.ts
  apps/member/src/hooks/queries/useBookLoanBorrowMutation.tsx
  apps/member/src/hooks/queries/useBookLoanExtendMutation.tsx
  apps/member/src/hooks/queries/useBookLoanRecordById.ts
  apps/member/src/hooks/queries/useBookLoanReturnMutation.tsx
  apps/member/src/hooks/queries/useBooks.ts
  apps/member/src/hooks/queries/useMembershipFee.ts
  apps/member/src/hooks/queries/useMembershipFeeMutation.ts
  apps/member/src/hooks/queries/useMyBookLoan.ts
  apps/member/src/hooks/queries/useSchedule.ts
  apps/member/src/hooks/queries/useUploadedFileMembershipFeeMutation.ts
  apps/member/src/pages/CalendarPage/CalendarPage.tsx
  apps/member/src/pages/ErrorPage/ErrorPage.tsx
  apps/member/src/pages/LibraryDetailPage/LibraryDetailPage.tsx
  apps/member/src/pages/LibraryPage/LibraryPage.tsx
  apps/member/src/pages/MainPage/MainPage.tsx
  apps/member/src/router/AppRouter.tsx
  apps/member/src/store/modal.ts
  apps/member/src/types/book.ts
  apps/member/src/types/membershipFee.ts
  apps/member/src/types/schedule.ts
  apps/member/src/utils/date.ts
  apps/member/vite.config.ts
  package.json
  packages/design-system/src/Input/Input.tsx
  yarn.lock
Labels: ✨ Feature, 🔨 Refactor
