Repository kgu-clab/clab-platforms, pull requests merged in 2024-01, with the labels that each got.

#4 Member Project 세팅 마이그레이션
  apps/member/.eslintrc.cjs
  apps/member/index.html
  apps/member/package.json
  apps/member/postcss.config.js
  apps/member/public/favicon.ico
  apps/member/public/logo.webp
  apps/member/public/not_found.webp
  apps/member/public/vite.svg
  apps/member/src/App.css
  apps/member/src/App.tsx
  apps/member/src/api/.gitkeep
  apps/member/src/components/.gitkeep
  apps/member/src/components/common/.gitkeep
  apps/member/src/constants/.gitkeep
  apps/member/src/constants/path.ts
  apps/member/src/hooks/.gitkeep
  apps/member/src/hooks/common/.gitkeep
  apps/member/src/hooks/queries/index.ts
  apps/member/src/hooks/queries/queryClient.ts
  apps/member/src/index.css
  apps/member/src/main.tsx
  apps/member/src/mocks/.gitkeep
  apps/member/src/pages/MainPage/MainPage.tsx
  apps/member/src/router/AppRouter.tsx
  apps/member/src/store/.gitkeep
  apps/member/src/styles/global.css
  apps/member/src/types/.gitkeep
  apps/member/src/utils/.gitkeep
  apps/member/tailwind.config.js
  apps/member/tsconfig.json
  apps/member/vite.config.ts
  yarn.lock
Labels: ✨ Feature

#5 Member Project 공용 컴포넌트 마이그레이션
  apps/member/src/assets/react.svg
  apps/member/src/assets/webp/fairy.webp
  apps/member/src/components/common/Button/Button.tsx
  apps/member/src/components/common/DropdownButton/DropdownButton.tsx
  apps/member/src/components/common/Footer/Footer.tsx
  apps/member/src/components/common/Image/Image.tsx
  apps/member/src/components/common/Linker/Linker.tsx
  apps/member/src/components/common/Nav/Nav.tsx
  apps/member/src/components/common/Panel/Panel.tsx
  apps/member/src/components/common/ScrollToTop/ScrollToTop.tsx
  apps/member/src/components/common/SelectButton/SelectButton.tsx
  apps/member/src/components/panels/AccountPanel/AccountPanel.tsx
  apps/member/src/components/panels/ActivityPanel/ActivityPanel.tsx
  apps/member/src/components/panels/AlarmPanel/AlarmPanel.tsx
  apps/member/src/components/panels/AttendanceFairyPanel/AttendanceFairyPanel.tsx
  apps/member/src/components/panels/BookPanel/BookPanel.tsx
  apps/member/src/components/panels/PanelAside/PanelAside.tsx
  apps/member/src/components/panels/ProfilePanel/ProfilePanel.tsx
  apps/member/src/components/panels/SetupPanel/SetupPanel.tsx
  apps/member/src/constants/path.ts
  apps/member/src/mocks/data/account.json
  apps/member/src/pages/ErrorPage/ErrorPage.tsx
  apps/member/src/pages/MainPage/MainPage.tsx
  apps/member/src/router/AppLayout.tsx
  apps/member/src/router/AppRouter.tsx
  apps/member/src/styles/global.css
  apps/member/src/utils/date.ts
  apps/member/src/utils/math.ts
Labels: ✨ Feature

#6 Root Prettier 설정
  .prettierrc
Labels: ⚙ Setup

#9 Member/develop
  apps/member/src/components/main/BirthdayList/BirthdayList.tsx
  apps/member/src/components/main/CommunityCard/CommunityCard.tsx
  apps/member/src/components/main/NewsCardList/NewsCardList.tsx
  apps/member/src/mocks/data/birthdayList.json
  apps/member/src/mocks/data/communityList.json
  apps/member/src/mocks/data/mainAlertList.json
  apps/member/src/mocks/data/mainBannerList.json
  apps/member/src/mocks/data/newsList.json
  apps/member/src/mocks/data/noticeList.json
  apps/member/src/pages/MainPage/MainPage.tsx
Labels: ✨ Feature

#10 Member MainPage 마이그레이션 완료
  apps/land/tsconfig.json
  apps/member/src/components/common/AlertList/AlertList.tsx
  apps/member/src/components/common/Button/Button.tsx
  apps/member/src/components/common/NewsCard/NewsCard.tsx
  apps/member/src/components/common/Panel/Panel.tsx
  apps/member/src/components/common/ProgressBar/ProgressBar.tsx
  apps/member/src/components/common/Section/Section.tsx
  apps/member/src/components/main/BirthdayList/BirthdayList.tsx
  apps/member/src/components/main/CommunitySection/CommunitySection.tsx
  apps/member/src/components/main/NewsCardList/NewsCardList.tsx
  apps/member/src/components/main/NewsCardSection/NewsCardSection.tsx
  apps/member/src/components/panels/AccountPanel/AccountPanel.tsx
  apps/member/src/components/panels/ActivityPanel/ActivityPanel.tsx
  apps/member/src/components/panels/AlarmPanel/AlarmPanel.tsx
  apps/member/src/components/panels/AttendanceFairyPanel/AttendanceFairyPanel.tsx
  apps/member/src/components/panels/BookPanel/BookPanel.tsx
  apps/member/src/components/panels/ProfilePanel/ProfilePanel.tsx
  apps/member/src/constants/.gitkeep
  apps/member/src/constants/path.ts
  apps/member/src/hooks/.gitkeep
  apps/member/src/mocks/data/blogList.json
  apps/member/src/mocks/data/hireList.json
  apps/member/src/mocks/data/itNewsList.json
  apps/member/src/mocks/data/newsList.json
  apps/member/src/mocks/data/noticeList.json
  apps/member/src/pages/MainPage/MainPage.tsx
  apps/member/src/styles/global.css
  apps/member/src/types/.gitkeep
  apps/member/src/types/button.ts
  apps/member/tsconfig.json
  apps/member/vite.config.ts
  tsconfig.json
Labels: ✨ Feature

#12 feat: MyPage 마이그레이션
  apps/member/src/components/my/HistorySection/HistorySection.tsx
  apps/member/src/components/my/ProfileSection/ProfileSection.tsx
  apps/member/src/mocks/data/myAlertList.json
  apps/member/src/mocks/data/myCommentList.json
  apps/member/src/mocks/data/myPostList.json
  apps/member/src/mocks/data/profile.json
  apps/member/src/pages/MyPage/MyPage.tsx
  apps/member/src/router/AppRouter.tsx
Labels: ✨ Feature

#14 feat: community 마이그레이션
  apps/member/src/components/common/Header/Header.tsx
  apps/member/src/components/common/Pagination/Pagination.tsx
  apps/member/src/components/community/CommunityWriteSection/CommunityWriteSection.tsx
  apps/member/src/components/community/DetailList/DetailList.tsx
  apps/member/src/components/community/PostCommentSection/PostCommentSection.tsx
  apps/member/src/components/community/PostProfileSection/PostProfileSection.tsx
  apps/member/src/components/community/PostTextSection/PostTextSection.tsx
  apps/member/src/components/community/PostTitleSection/PostTitleSection.tsx
  apps/member/src/components/main/CommunitySection/CommunitySection.tsx
  apps/member/src/constants/path.ts
  apps/member/src/mocks/data/communityList.json
  apps/member/src/mocks/data/gassipList.json
  apps/member/src/mocks/data/graduatedList.json
  apps/member/src/mocks/data/hireList.json
  apps/member/src/mocks/data/newsList.json
  apps/member/src/mocks/data/noticeList.json
  apps/member/src/mocks/data/postData.json
  apps/member/src/pages/CommunityDetailPage/CommunityDetailPage.tsx
  apps/member/src/pages/CommunityPage/CommunityPage.tsx
  apps/member/src/pages/CommunityPostPage/CommunityPostPage.tsx
  apps/member/src/pages/CommunityWritePage/CommunityWritePage.tsx
  apps/member/src/router/AppRouter.tsx
Labels: ✨ Feature

#16 Member/develop
  .gitignore
  README.md
  apps/member/README.md
  apps/member/src/components/common/Button/Button.style.ts
  apps/member/src/components/common/Button/Button.tsx
  apps/member/src/components/common/Comment/Comment.tsx
  apps/member/src/components/common/CommentInput/CommentInput.tsx
  apps/member/src/components/common/Header/Header.tsx
  apps/member/src/components/common/Input/Input.tsx
  apps/member/src/components/common/Pagination/Pagination.tsx
  apps/member/src/components/common/Post/Post.tsx
  apps/member/src/components/common/Select/Select.tsx
  apps/member/src/components/common/Share/Share.tsx
  apps/member/src/components/common/Table/Table.tsx
  apps/member/src/components/common/Textarea/Textarea.tsx
  apps/member/src/components/community/PostCommentSection/PostCommentSection.tsx
  apps/member/src/components/main/BirthdayList/BirthdayList.tsx
  apps/member/src/components/main/CommunitySection/CommunitySection.tsx
  apps/member/src/components/my/HistorySection/HistorySection.tsx
  apps/member/src/components/my/ProfileSection/ProfileSection.tsx
  apps/member/src/components/panels/PanelAside/PanelAside.tsx
  apps/member/src/constants/api.ts
  apps/member/src/constants/message.ts
  apps/member/src/constants/path.ts
  apps/member/src/mocks/data/freeBoardList.json
  apps/member/src/mocks/data/graduatedBoardList.json
  apps/member/src/mocks/data/hireBoardList.json
  apps/member/src/mocks/data/itNewsBoardList.json
  apps/member/src/mocks/data/myAlertList.json
  apps/member/src/mocks/data/myCommentList.json
  apps/member/src/mocks/data/myPostList.json
  apps/member/src/mocks/data/newsList.json
  apps/member/src/mocks/data/noticeBoardList.json
  apps/member/src/mocks/data/noticeList.json
  apps/member/src/mocks/data/post.json
  apps/member/src/mocks/data/profile.json
  apps/member/src/mocks/data/qnaBoardList.json
  apps/member/src/mocks/mocks.ts
  apps/member/src/pages/CommunityDetailPage/CommunityDetailPage.tsx
  apps/member/src/pages/CommunityPage/CommunityPage.tsx
  apps/member/src/pages/CommunityPostPage/CommunityPostPage.tsx
  apps/member/src/pages/CommunityWritePage/CommunityWritePage.tsx
  apps/member/src/pages/MainPage/MainPage.tsx
  apps/member/src/pages/MyPage/MyPage.tsx
  apps/member/src/router/AppLayout.tsx
  apps/member/src/router/AppRouter.tsx
  apps/member/src/types/button.ts
  apps/member/src/types/community.ts
Labels: ✨ Feature

#17 feat: calendar 마이그레이션
  apps/member/src/components/calendar/CalendarSection/CalendarSection.tsx
  apps/member/src/components/calendar/ShowDate/ShowDate.tsx
  apps/member/src/components/calendar/calendarUtils/calendarUtils.tsx
  apps/member/src/mocks/data/schedule.json
  apps/member/src/pages/CalendarPage/CalendarPage.tsx
  apps/member/src/router/AppRouter.tsx
Labels: ✨ Feature

#19 feat: support 마이그레이션
  apps/member/src/assets/support/check.svg
  apps/member/src/assets/support/checking.svg
  apps/member/src/assets/support/document.svg
  apps/member/src/assets/support/icons.tsx
  apps/member/src/assets/support/next.svg
  apps/member/src/components/common/Icons/Icons.tsx
  apps/member/src/components/support/FormInput/FormInput.tsx
  apps/member/src/components/support/ProcessSection/ProcessSection.tsx
  apps/member/src/components/support/RequestForm/RequestForm.tsx
  apps/member/src/pages/SupportPage/SupportPage.tsx
  apps/member/src/router/AppRouter.tsx
Labels: ✨ Feature

#20 feat: library 마이그레이션
  apps/member/src/components/common/Skeleton/SkeletonImage.tsx
  apps/member/src/components/library/BookDetailSection/BookDetailSection.tsx
  apps/member/src/components/library/LibraryBookList/LibraryBookList.tsx
  apps/member/src/components/library/LibraryNewBookSection/LibraryNewBookSection.tsx
  apps/member/src/components/library/LibraryOwnBookSection/LibraryOwnBookSection.tsx
  apps/member/src/constants/path.ts
  apps/member/src/mocks/data/bookCollection.json
  apps/member/src/pages/LibraryDetailPage/LibraryDetailPage.tsx
  apps/member/src/pages/LibraryPage/LibraryPage.tsx
  apps/member/src/router/AppRouter.tsx
Labels: ✨ Feature

#23 feat: group 마이그레이션
  apps/member/src/components/common/Skeleton/SkeletonImage.tsx
  apps/member/src/components/group/AssignmentFeedbackSection/AssignmentFeedbackSection.tsx
  apps/member/src/components/group/AssignmentUploadSection/AssignmentUploadSection.tsx
  apps/member/src/components/group/CreateForm/CreateForm.tsx
  apps/member/src/components/group/DetailInfoSection/DetailInfoSection.tsx
  apps/member/src/components/group/GroupCard/GroupCard.tsx
  apps/member/src/components/group/GroupMain/GroupMain.tsx
  apps/member/src/components/group/GroupNoticeAlertSection/GroupNoticeAlertSection.tsx
  apps/member/src/components/group/GroupNoticeSection/GroupNoticeSection.tsx
  apps/member/src/components/group/NoticeDetailSection/NoticeDetailSection.tsx
  apps/member/src/components/group/StudentSection/StudentSection.tsx
  apps/member/src/components/group/WeekDetail/WeekDetail.tsx
  apps/member/src/components/group/WeeklyActivitySection/WeeklyActivitySection.tsx
  apps/member/src/constants/path.ts
  apps/member/src/mocks/data/groupList.json
  apps/member/src/pages/GroupAssignmentPage/GroupAssignmentPage.tsx
  apps/member/src/pages/GroupCreatePage/GroupCreatePage.tsx
  apps/member/src/pages/GroupDetailPage/GroupDetailPage.tsx
  apps/member/src/pages/GroupNoticeDetailPage/GroupNoticeDetailPage.tsx
  apps/member/src/pages/GroupPage/GroupPage.tsx
  apps/member/src/pages/GroupStudentPage/GroupStudentPage.tsx
  apps/member/src/router/AppRouter.tsx
Labels: ✨ Feature

#27 Develop
  apps/member/src/assets/support/SupportIcons.tsx
  apps/member/src/assets/support/check.svg
  apps/member/src/assets/support/checking.svg
  apps/member/src/assets/support/document.svg
  apps/member/src/assets/support/icons.tsx
  apps/member/src/assets/support/next.svg
  apps/member/src/components/calendar/Calendar/Calendar.tsx
  apps/member/src/components/calendar/Calendar/Calendar.utils.tsx
  apps/member/src/components/calendar/CalendarSchedule/CalendarSchedule.tsx
  apps/member/src/components/calendar/CalendarSection/CalendarSection.tsx
  apps/member/src/components/calendar/calendarUtils/calendarUtils.tsx
  apps/member/src/components/common/Header/Header.tsx
  apps/member/src/components/common/Icons/Icons.tsx
  apps/member/src/components/common/Image/Image.tsx
  apps/member/src/components/common/Linker/Linker.tsx
  apps/member/src/components/common/Skeleton/SkeletonImage.tsx
  apps/member/src/components/group/ApplyForm/ApplyForm.tsx
  apps/member/src/components/group/AssignmentFeedbackSection/AssignmentFeedbackSection.tsx
  apps/member/src/components/group/AssignmentUploadSection/AssignmentUploadSection.tsx
  apps/member/src/components/group/GroupCard/GroupCard.tsx
  apps/member/src/components/group/GroupDetailSection/GroupDetailSection.tsx
  apps/member/src/components/group/GroupNoticeAlertSection/GroupNoticeAlertSection.tsx
  apps/member/src/components/group/GroupNoticeSection/GroupNoticeSection.tsx
  apps/member/src/components/group/NoticeDetailSection/NoticeDetailSection.tsx
  apps/member/src/components/group/StudentSection/StudentSection.tsx
  apps/member/src/components/group/WeekDetail/WeekDetail.tsx
  apps/member/src/components/group/WeeklyActivitySection/WeeklyActivitySection.tsx
  apps/member/src/components/library/BookDetailSection/BookDetailSection.tsx
  apps/member/src/components/library/LibraryBookList/LibraryBookList.tsx
  apps/member/src/components/library/LibraryNewBookSection/LibraryNewBookSection.tsx
  apps/member/src/components/library/LibraryOwnBookSection/LibraryOwnBookSection.tsx
  apps/member/src/components/support/FormInput/FormInput.tsx
  apps/member/src/components/support/ProcessSection/ProcessSection.tsx
  apps/member/src/components/support/RequestForm/RequestForm.tsx
  apps/member/src/constants/path.ts
  apps/member/src/constants/state.ts
  apps/member/src/mocks/data/groupList.json
  apps/member/src/pages/CalendarPage/CalendarPage.tsx
  apps/member/src/pages/GroupApplyPage/GroupApplyPage.tsx
  apps/member/src/pages/GroupAssignmentPage/GroupAssignmentPage.tsx
  apps/member/src/pages/GroupDetailPage/GroupDetailPage.tsx
  apps/member/src/pages/GroupNoticeDetailPage/GroupNoticeDetailPage.tsx
  apps/member/src/pages/GroupPage/GroupPage.tsx
  apps/member/src/pages/GroupStudentPage/GroupStudentPage.tsx
  apps/member/src/pages/LibraryDetailPage/LibraryDetailPage.tsx
  apps/member/src/pages/LibraryPage/LibraryPage.tsx
  apps/member/src/pages/SupportPage/SupportPage.tsx
  apps/member/src/router/AppRouter.tsx
  packages/design-system/src/Button/Button.style.ts
Labels: ✨ Feature, 🔨 Refactor
