Repository kgu-clab/clab-platforms, pull requests merged in 2024-03, with the labels that each got.

#58 Auth 프로토콜 변경
  apps/auth/app/api/auth.ts
  apps/auth/app/constants/api.ts
  apps/auth/app/hooks/queries/useLoginMutation.ts
  apps/auth/app/hooks/queries/useTwoFactorLoginMutation.ts
Labels: 🔨 Refactor

#65 commit-lint 설정 완료
  .husky/commit-msg
  README.md
  commitlint.config.js
  package.json
  yarn.lock
Labels: ⚙ Setup

#68 BUG-(7, 8, 10, 14) 버그 개선 완료
  apps/member/src/api/book.ts
  apps/member/src/api/interceptors.ts
  apps/member/src/api/membershipFee.ts
  apps/member/src/api/uploadedFile.ts
  apps/member/src/components/common/Select/Select.tsx
  apps/member/src/components/library/BookDetailSection/BookDetailSection.tsx
  apps/member/src/components/panels/AccountPanel/AccountPanel.tsx
  apps/member/src/components/panels/BookPanel/BookPanel.tsx
  apps/member/src/components/panels/PanelAside/PanelAside.tsx
  apps/member/src/components/panels/ProfilePanel/ProfilePanel.tsx
  apps/member/src/components/panels/SetupPanel/SetupPanel.tsx
  apps/member/src/components/support/RequestForm/RequestForm.tsx
  apps/member/src/constants/api.ts
  apps/member/src/constants/default.ts
  apps/member/src/constants/key.ts
  apps/member/src/constants/select.ts
  apps/member/src/hooks/queries/index.ts
  apps/member/src/hooks/queries/useBookDetails.ts
  apps/member/src/hooks/queries/useBookLoanBorrowMutation.tsx
  apps/member/src/hooks/queries/useBookLoanExtendMutation.tsx
  apps/member/src/hooks/queries/useBookLoanRecordById.ts
  apps/member/src/hooks/queries/useBookLoanReturnMutation.tsx
  apps/member/src/hooks/queries/useMembershipFeeMutation.ts
  apps/member/src/hooks/queries/useMyBookLoan.ts
  apps/member/src/hooks/queries/useUploadedFileMembershipFeeMutation.ts
  apps/member/src/main.tsx
  apps/member/src/pages/LibraryDetailPage/LibraryDetailPage.tsx
  apps/member/src/types/api.ts
  apps/member/src/utils/date.ts
  apps/member/src/utils/math.ts
Labels: 🐞 Bug, 🔨 Refactor

#70 chore: README.md 프로젝트 특징, FAQ 문의사항 추가 (#69)
  README.md
Labels: 🗂️ Documentation

#73 feat(auth): oauth 회원 사이트 추가 (#72)
  README.md
  apps/auth/app/constants/api.ts
Labels: ✨ Feature

#74 open-bata 출시 전 UI 개선 완료
  apps/member/.env.production
  apps/member/package.json
  apps/member/src/api/interceptors.ts
  apps/member/src/api/member.ts
  apps/member/src/api/uploadedFile.ts
  apps/member/src/components/common/Comment/Comment.tsx
  apps/member/src/components/common/CommentInput/CommentInput.tsx
  apps/member/src/components/common/Footer/Footer.tsx
  apps/member/src/components/common/Header/Header.tsx
  apps/member/src/components/common/LoginButton/LoginButton.tsx
  apps/member/src/components/common/Nav/Nav.tsx
  apps/member/src/components/common/Post/Post.tsx
  apps/member/src/components/community/PostCommentSection/PostCommentSection.tsx
  apps/member/src/components/main/NewsCardSection/NewsCardSection.tsx
  apps/member/src/components/my/HistorySection/HistorySection.tsx
  apps/member/src/components/my/ProfileSection/ProfileSection.tsx
  apps/member/src/components/panels/ActivityPanel/ActivityPanel.tsx
  apps/member/src/components/panels/AlarmPanel/AlarmPanel.tsx
  apps/member/src/components/panels/BookPanel/BookPanel.tsx
  apps/member/src/components/panels/PanelAside/PanelAside.tsx
  apps/member/src/components/panels/ProfilePanel/ProfilePanel.tsx
  apps/member/src/components/support/RequestForm/RequestForm.tsx
  apps/member/src/constants/api.ts
  apps/member/src/constants/environment.ts
  apps/member/src/hooks/queries/useActivityGroup.ts
  apps/member/src/hooks/queries/useMyActivity.ts
  apps/member/src/hooks/queries/useMyNotifications.ts
  apps/member/src/hooks/queries/useMyProfile.ts
  apps/member/src/hooks/queries/usePosts.ts
  apps/member/src/hooks/queries/useSchedule.ts
  apps/member/src/pages/CalendarPage/CalendarPage.tsx
  apps/member/src/pages/CommunityPostPage/CommunityPostPage.tsx
  apps/member/src/pages/CommunityWritePage/CommunityWritePage.tsx
  apps/member/src/pages/LoginPage/LoginPage.tsx
  apps/member/src/pages/MainPage/MainPage.tsx
  apps/member/src/pages/MyPage/MyPage.tsx
  apps/member/src/types/community.ts
  apps/member/src/types/post.ts
  apps/member/src/types/profile.ts
  apps/member/src/utils/community.ts
  apps/member/src/utils/group.ts
  apps/member/src/utils/style.tsx
Labels: 🔨 Refactor

#77 프로필 수정 시 비밀번호 초기화 개선
  apps/member/src/api/member.ts
  apps/member/src/components/my/ProfileSection/ProfileSection.tsx
  apps/member/src/constants/message.ts
  apps/member/src/hooks/common/useModal.ts
  apps/member/src/hooks/queries/useUserInfoMutation.ts
  apps/member/src/store/modal.ts
Labels: 🐞 Bug, 🔨 Refactor

#79 Update README.md
  README.md
Labels: 🗂️ Documentation

#81 refactor(auth): api versioning 대응 (#80)
  apps/auth/app/constants/api.ts
Labels: 🔨 Refactor
